version: 2

py_image: &py_image
  image: python:3.6

build_key: &build_key
  key: drftoolbox-build-v1-{{ checksum "Pipfile.lock" }}

attach: &attach
  attach_workspace:
    at: .

restore_venv: &restore_venv
  restore_cache:
    *build_key


workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - coveralls:
          requires:
            - test


jobs:
  build:
    docker:
      - *py_image
    steps:
      - checkout
      - *restore_venv
      - run:
          name: install dependencies
          command: |
            [ -d "venv" ] || (make venv && make init)
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - save_cache:
          <<: *build_key
          paths:
            - venv
  test:
    docker:
      - *py_image
    steps:
      - *attach
      - *restore_venv
      - run:
          name: test
          command: |
            make venv
            make coverage
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
  lint:
    docker:
      - *py_image
    steps:
      - *attach
      - *restore_venv
      - run:
          name: lint
          command: |
            make venv
            make lint
  coveralls:
    docker:
      - *py_image
    steps:
      - *attach
      - *restore_venv
      - run:
          name: coveralls
          command: |
            make venv
            coveralls --rcfile=.coveragerc
  tag:
    docker:
      - *py_image
    steps:
      - *attach
      - *restore_venv
